### PR TITLE
Add support for building with CMake

### PR DESCRIPTION
**Pull request by jcelerier**
This makes it much easier to change build settings without having to open a GUI and to integrate with other projects

### CODE REVIEW

**Comment by bangnoise** [comment]
Personally I am not keen on this idea. More than one build method adds labour for maintainers and contributors.

`xcodebuild` allows you to change build settings from the command line, and can be integrated into CMake builds for the host project.

**Comment by jcelerier** [comment]
>  and can be integrated into CMake builds for the host project. 

Is there a way to ensure that the xcode will use the same toolchain and compiler/linker/... flags than the host build automatically ? e.g. -flto, -march=whatever, PGO, etc...

**Comment by vade** [comment]
FWIW I agree with @bangnoise - I absolutely refuse to support building with CMake ;)

**Comment by bangnoise** [comment]
> > and can be integrated into CMake builds for the host project.
> 
> Is there a way to ensure that the xcode will use the same toolchain and compiler/linker/... flags than the host CMake build automatically ? e.g. -flto, -march=whatever, PGO, etc...

`man xcodebuild` - sorry not to be more helpful than that

**Comment by vkedwardli** [comment]
Just in case anyone else need CMake support with Metal + Static Library: https://github.com/Syphon/Syphon-Framework/compare/main...vkedwardli:Syphon-Framework:main

Working with Xcode generator and Ninja build
CI builds here: https://github.com/flyinghead/flycast/pull/1126

**Pull request closed without merging**
